### PR TITLE
Implement `lingo init` for Zephyr and Native

### PR DESCRIPTION
**Pull request by erlingrj**
This PR implements the `lingo init` command for the Zephyr and the default (Native) platform. I went with the following command structure:

`lingo init --platform/-p zephyr --language/-l c`

We use git to clone the `lf-west-template` down from Github and populate a project directory.

### CODE REVIEW

**Review by revol-xut — APPROVED** [review]
Looks really good. Did u test it ?

**Comment by erlingrj** [comment]
Did you understand the clippy output? The `lingo build` command is not successful because it tries to invoke: `lfc --output` (see FIXME in `lfc.rs`). What is the intention of this build step?

**Comment by revol-xut** [comment]
I was just some problem with clap 3 I updated to clap 4 and the issue resolved itself.

**Comment by revol-xut** [comment]
This panic there is that the CodeGenerator expects an absolute path to lfc and if the path doesn't exists we can only panic.

**Comment by erlingrj** [comment]
I think in order to merge this we should:
- [ ] Implement the blacklist-based copying of the west-template
- [ ] Make sure TargetLangauge is default C with platform Zephyr.

**Pull request merged**
